server:
  port: 8080

spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Vary, RETAIN_FIRST
            - id: USER-SERVICE-DOCS
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user-service/v3/api-docs
              filters:
                - RewritePath=/user-service/v3/api-docs, /v3/api-docs
                - AddRequestHeader=X-Forwarded-Prefix, /api/users
                - PreserveHostHeader
            - id: PRODUCT-SERVICE
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/api/products/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Vary, RETAIN_FIRST
            - id: PRODUCT-SERVICE-DOCS
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/product-service/v3/api-docs
              filters:
                - RewritePath=/product-service/v3/api-docs, /v3/api-docs
                - AddRequestHeader=X-Forwarded-Prefix, /api/products
                - PreserveHostHeader
            - id: COLLECTION-SERVICE
              uri: lb://COLLECTION-SERVICE
              predicates:
                - Path=/api/collections/**
              filters:
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Vary, RETAIN_FIRST
            - id: COLLECTION-SERVICE-DOCS
              uri: lb://COLLECTION-SERVICE
              predicates:
                - Path=/collection-service/v3/api-docs
              filters:
                - RewritePath=/collection-service/v3/api-docs, /v3/api-docs
                - AddRequestHeader=X-Forwarded-Prefix, /api/collections
                - PreserveHostHeader

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: User Service
        url: /user-service/v3/api-docs
      - name: Product Service
        url: /product-service/v3/api-docs
      - name: Collection Service
        url: /collection-service/v3/api-docs
  use-management-port: false


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true