spring:
  cloud:
    discovery:
      enabled: false
  application:
    name: USER-SERVICE
  profiles:
    active: "@env@"
  mail:
    host: smtp.gmail.com
    port: 587
    username: MySyna.pro@gmail.com
    password: usun wzpk ipjt sosb
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

server:
  port: 8082

